### ISSUE TITLE
Can't execute command line from HDInsight Map/Reduce Activity in ADF

### ISSUE THREAD

**Issue by briancuster** [Azure-Samples/data-factory-r-server-apache-spark-pipeline#1]
When trying to duplicate the work presented herein with my requirements I am unable to get the solution to work.  The data factory runs but the HDInsight job masquerading as an HDInsight map/reduce job does not run on the cluster.  There is virtually no error message when this is attempted other than a cryptic message about trying to access storage using http.

**Comment by udayankumar** [comment]
Are you getting any errors when you go through the tutorial without any modifications? I want to rule out any issues introduced by the age of this sample since this sample is not actively maintained.

**Comment by briancuster** [comment]
Actually, I didn’t duplicate exactly your work.  I improvised your work by creating a ADF pipeline that has three HDInsight MapReduce activities using the jar file you pointed to in your work to run a command line to execute RevoScaleR functions to import data into XDF format (1) and then (2) train a DTree model and then (3) train a cluster model.  The issue is that the jar file never appears to be executed.  All I get is some cryptic message from the cluster that it can’t connect to a storage account using http.  Thanks!

Brian Custer

________________________________

**Comment by udayankumar** [comment]
I would recommend following this tutorial and duplicating the steps. This way I can replicate the errors.

**Comment by briancuster** [comment]
I will try to do this if I have the time.  The project I was working on is wrapping up this week so I may not have the time to execute your example but I will try so that I can pass along anything that I find out to my client.  Thanks for checking in with me.

Brian Custer

________________________________

**Comment by briancuster** [comment]
I decided to go ahead with following the tutorial.  I’m deploying the resources now to my account.  I will let you know when I’m done and what the results were.  Thanks again for contacting me.

Brian Custer

________________________________

**Comment by briancuster** [comment]
Hi, well I executed the code and have my data factory and cluster up and running but the data factory isn’t executing.  Any idea why it wouldn’t execute?  I changed the dates on the start and end times to present day.  I also noticed that you have the interval set to monthly.  Should I set that to daily and re-do the data sets?

Brian Custer

________________________________

**Comment by udayankumar** [comment]
Can you start the pipeline manually? there should be button to start the pipeline manually

**Comment by briancuster** [comment]
Actually, no.  There isn’t a button to start the pipeline manually.  It can only be started by the scheduling engine as far as I know or using Azure Automation and a powershell command.  I guess I could start it that way.

Brian Custer

________________________________

**Comment by udayankumar** [comment]
Either way should be fine as long as you able to start is manually. Previously, I have used portal to manually start a pipeline

**Comment by briancuster** [comment]
I can’t find a way to do that given the V1 interface.  I’ve worked a lot with Data Factory and am not aware of a button or UI affordance that can be used to execute a DF on the fly.  I’ll fiddle with the dates and see if I can get it to execute.

Brian Custer

________________________________

**Comment by udayankumar** [comment]
the scoring pipeline is set to pause. Have you set the parameter to false? Sorry I don't remember everything about the solution .. but this is what the readme says  
```
Start the scoring pipeline
a. By default, the scoring pipeline is set to pause. This is because it needs the 'model' file, which is generated upon the first run of the training pipeline. And since the scoring pipeline's running frequency is independent of the training pipeline, we have not added any dependencies between them. Therefore, the scoring pipeline is paused and we manually start it when the 'model' file is available.
b. To start the scoring pipeline, we need to change a config parameter for that pipeline through portal. Find the Data Factory that we created earlier and click - Author and Deploy, then expand Pipelines and click on datafactoryscoring pipeline. Towards the bottom, there is a key - isPaused, change the value for this key from true to false. Now click on Deploy button to activate these changes.
c. Now go back to the Diagram view and click the finalOutputDatasetScoring dataset, check the runs, if they have still not started, you can manually start the run (generally it take a moment before the pipeline starts). Now once the run is complete, similar to the training pipeline, one can check the status of the pipeline run.
d. If the status is Succeeded, then the attached storage container has a blob folder named 'scoringOutput'. This file contains the output (tip amount) prediction for the scoring dataset in csv format.```

**Comment by briancuster** [comment]
I have it executing now.  I just went in and changed the interval to day instead of Month and set the start and end dates to today’s date.  It’s executing now, I’ll let you know how it goes.

Brian Custer

________________________________

**Comment by briancuster** [comment]
It worked just fine…at least the training part did.  I’m scoring right now.  I can’t explain why your example works but mine doesn’t.  I have it set up almost the same way.  The only difference between my experiment and yours is that I don’t copy the data to storage like you do.  My data is in an ADLA store that I intend to connect to via a service principal.  However, as I said previously, I can’t even get the jar file to execute in my example.  The cluster does not execute the jar file and instead complains about not being able to access a storage account using http.  It’s really weird and very frustrating.

Brian Custer

________________________________

**Comment by udayankumar** [comment]
Are you able to run the task from a node directly i.e. login to the machine and then firing the exact same command that you  give to the jar file?

**Comment by briancuster** [comment]
Yes, we have been running the command line using ssh for quite some time now.  So we were trying to get it to run using your approach but I can’t even get the map reduce program to execute.  If fails way before then.  That’s what is so frustrating about this…I don’t even get a chance to see if the command line works because the jar program doesn’t execute on the cluster.

Brian Custer

________________________________

**Comment by udayankumar** [comment]
would you mind sharing the template files. Also highlight any section that
you have modified. I can take a look

**Comment by briancuster** [comment]
Before I do that, I think I know why it is not working on my side.  I do not have my scripts and data on the cluster storage.  Instead, the scripts are located on another storage account and the data is located in ADLA storage.  Consequently, I believe the cluster is unable to connect to the storage account where the scripts are stored and thus cannot execute the jar file that is there.  Hence, I will need to modify my ARM template to do a linked deployment.  First I will have to create a storage account and copy the scripts to the storage account.  Then, I will have to create the HDInsight cluster and connect it to the storage account.  Then I will have to run a script on all of the cluster nodes that connect it to ADLA.  I think if I can do that I can get it working.

Brian Custer

________________________________

**Comment by briancuster** [comment]
I am supplying the data factory json that I am using to attempt to execute the jar file.  It isn’t executing currently, the logs indicate that the file doesn’t even get a chance to execute.  Here’s the data factory json:

{
    "name": "PL-HDInsight",
    "properties": {
        "description": "Submit test scripts",
        "activities": [
            {
                "type": "HDInsightMapReduce",
                "typeProperties": {
                    "className": "com.adf.jobonhdi.JobOnHdiLauncher",
                    "jarFilePath": "scripts/jar/com.adf.adfjobonhdi.jar",
                    "jarLinkedService": "LS-AzureStorage",
                    "arguments": [
                        "--files",
                        "wasb://scripts@loyaltyadvisordevsa.blob.core.windows.net/jar/com.adf.appsample.jar, wasb://scripts@loyaltyadvisordevsa.blob.core.windows.net/R/Script.R",
                        "--command",
                        "source /usr/lib64/microsoft-r/8.0/hadoop/RevoHadoopEnvVars.site; Revo64 CMD BATCH Script.R"
                    ]
                },
                "outputs": [
                    {
                        "name": "DS-BlobOutputFinal"
                    }
                ],
                "policy": {
                    "timeout": "01:00:00",
                    "concurrency": 1,
                    "retry": 1
                },
                "scheduler": {
                    "frequency": "Day",
                    "interval": 1
                },
                "name": "MapReduceActivity",
                "linkedServiceName": "LS-HDInsight"
            }
        ],
        "start": "2017-12-20T01:00:00Z",
        "end": "2017-12-21T01:00:00Z",
        "isPaused": false,
        "hubName": "loyaltyadvisordevadf_hub",
        "pipelineMode": "Scheduled"
    }
}

Brian Custer

________________________________

**Comment by udayankumar** [comment]
Are you able to run these commands on any of the nodes directly?

source /usr/lib64/microsoft-r/8.0/hadoop/RevoHadoopEnvVars.site
Revo64 CMD BATCH Script.R

I am not sure but if the microsoft R version is different then this path
will change.

**Comment by briancuster** [comment]
Yeah, we were able to.  That’s been tested.  The project is over now so I guess I’m over it for now.  Maybe it will be brought back up at a later date.  Thanks again for trying to help me.

Brian Custer

________________________________

**Comment by udayankumar** [comment]
I wish we had more time to debug the issue. I am closing this issue now but please feel free to recreate or reopen this issue in the future.

**Comment by briancuster** [comment]
I wish we did too as I really wanted to get our application working before the project ended.  Perhaps we’ll talk again.  Your work was quite interesting and has a lot of applicability to what I work on.  I was also working on a custom .Net activity that spins up a cluster on demand and then executes a command line using ssh.  I’m almost done with it and will be testing it soon.  Thanks again for all of your help.
